# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 600
# Issues with these labels will never be considered stale
exemptLabels:
  - community
  - bug
  - paused
  - good first issue
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  any activity in 90 days. It will be closed in 600 days if no further activity
  occurs. Thank you for your contributions to tedana:tada: !
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
