codecov:
  notify:
    require_ci_to_pass: yes

fixes:
  - "/tmp/src/tedana/tedana/::tedana/"  # move path

coverage:
  status:
    project:
      default:
        # basic
        target: 0
        threshold: null
    patch:
      default:
        target: 0
        threshold: null
