codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        # basic
        target: 0
        threshold: null
    patch:
      default:
        target: 0
        threshold: null

ignore:
  - "tedana/tests/"
  - "tedana/due.py"
  - "tedana/_version.py"
  - "tedana/info.py"
