# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: emdupre/meica-docker:0.0.4

    working_directory: /home/neuro/code/

    steps:
      - checkout

      - run:
          name: Download input test data
          command: curl -L -o /home/neuro/data/zcat_ffd.nii.gz https://www.dropbox.com/s/ljeqskdmnc6si9d/zcat_ffd.nii.gz?dl=0

      - run:
          name: Download expected output data
          command: |
            curl -L -o /home/neuro/data/test_TED.tar.gz https://www.dropbox.com/s/x5xhzs3x6p3ukjl/test_TED.tar.gz?dl=0
            tar -xvzf /home/neuro/data/test_TED.tar.gz --no-same-owner -C /home/neuro/data/


      - run:
          name: Create test environment
          command: |
            conda create --name venv python=3.6
            source activate venv
            pip install pytest
            pip install -r requirements.txt
            python setup.py install

      - run:
          name: Run tests
          command: |
            source activate venv
            py.test ./tedana/tests/test_tedana.py
          no_output_timeout: "40m"
          post: bash <(curl -s https://codecov.io/bash)

      - store_artifacts:
          path: /home/neuro/code/TED.zcat_ffd/
