# Generated by Neurodocker v0.2.0-12-g1a1c6f6.
#
# Thank you for using Neurodocker. If you discover any issues
# or ways to improve this software, please submit an issue or
# pull request on our GitHub repository:
#     https://github.com/kaczmarj/neurodocker
#
# Timestamp: 2017-08-30 19:05:17

FROM ubuntu:trusty

ARG DEBIAN_FRONTEND=noninteractive

#----------------------------------------------------------
# Install common dependencies and create default entrypoint
#----------------------------------------------------------
ENV LANG="C.UTF-8" \
    LC_ALL="C.UTF-8" \
    ND_ENTRYPOINT="/neurodocker/startup.sh"
RUN apt-get update -qq && apt-get install -yq --no-install-recommends  \
    	bzip2 ca-certificates curl unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && chmod 777 /opt && chmod a+s /opt \
    && mkdir -p /neurodocker \
    && if [ ! -f "$ND_ENTRYPOINT" ]; then \
         echo '#!/usr/bin/env bash' >> $ND_ENTRYPOINT \
         && echo 'set +x' >> $ND_ENTRYPOINT \
         && echo 'if [ -z "$*" ]; then /usr/bin/env bash; else $*; fi' >> $ND_ENTRYPOINT; \
       fi \
    && chmod -R 777 /neurodocker && chmod a+s /neurodocker
ENTRYPOINT ["/neurodocker/startup.sh"]

RUN apt-get update -qq && apt-get install -yq --no-install-recommends git vim \
    && apt-get clean \
&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Create new user: neuro
RUN useradd --no-user-group --create-home --shell /bin/bash neuro
USER neuro

#------------------
# Install Miniconda
#------------------
ENV CONDA_DIR=/opt/conda \
    PATH=/opt/conda/bin:$PATH
RUN echo "Downloading Miniconda installer ..." \
    && miniconda_installer=/tmp/miniconda.sh \
    && curl -sSL -o $miniconda_installer https://repo.continuum.io/miniconda/Miniconda3-4.3.31-Linux-x86_64.sh \
    && /bin/bash $miniconda_installer -f -b -p $CONDA_DIR \
    && rm -f $miniconda_installer \
    && conda config --system --prepend channels conda-forge \
    && conda config --system --set auto_update_conda false \
    && conda config --system --set show_channel_urls true \
    && conda update -y -q --all && sync \
    && conda clean -tipsy && sync

#-----------------------------
# Create py3 conda environment
#-----------------------------
RUN conda create -y -q --name py36 python=3.6 \
    	numpy scikit-learn mdp nilearn scipy 'nibabel>=2.1.0' \
    && sync && conda clean -tipsy && sync \
    && bash -c "source activate py36 \
    && pip install -q --no-cache-dir \
        https://github.com/ME-ICA/tedana/archive/master.tar.gz" \
    && sync \
    && sed -i '$isource activate py36' $ND_ENTRYPOINT

#------------------------------
# Create py27 conda environment
#------------------------------
RUN conda create -y -q --name py27 python=2.7 \
        numpy scikit-learn mdp nilearn scipy 'nibabel>=2.1.0' \
    && sync && conda clean -tipsy && sync \
    && bash -c "source activate py27 \
    && pip install -q --no-cache-dir \
        https://github.com/ME-ICA/tedana/archive/master.tar.gz" \
    && sync

USER root

# User-defined instruction
RUN mkdir /home/neuro/code /home/neuro/data

WORKDIR /home/neuro
