[tox]
requires =
  tox>=4
  tox-uv
envlist =
  py3{9,10,11,12,13}-{latest,pre}
  py39-min
skip_missing_interpreters = true

# Configuration that allows us to split tests across GitHub runners effectively
[gh-actions]
python =
  3.9: py39
  3.10: py310
  3.11: py311
  3.12: py312
  3.13: py313

[gh-actions:env]
DEPENDS =
  min: min
  latest: latest
  pre: pre

[testenv]
description = Pytest with coverage
labels = test
pass_env =
  # getpass.getuser() sources for Windows:
  LOGNAME
  USER
  LNAME
  USERNAME
  # Pass user color preferences through
  PY_COLORS
  FORCE_COLOR
  NO_COLOR
  CLICOLOR
  CLICOLOR_FORCE
  PYTHON_GIL

# Configure min/pre-release environments
extras =
  {min,pre}: tests
pip_pre =
  pre: true
setenv =
  pre: PIP_EXTRA_INDEX_URL=https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
  pre: UV_INDEX=https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
  pre: UV_INDEX_STRATEGY=unsafe-best-match
uv_resolution =
  min: lowest-direct

# Configure latest to use uv sync to ensure that locked versions are tested.
# uv-venv-lock-runner and uv_resolution don't mix nicely, so override the normal install
skip_install =
  latest: True
commands_pre =
  latest: uv sync --active --extra=tests

commands =
  pytest --skipintegration --cov-append --cov-report term-missing --cov=tedana tedana {posargs}
